apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-rs-watcher-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-rs-watcher-combined-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-rs-watcher-combined-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-rs-watcher-combined-role
subjects:
- kind: ServiceAccount
  name: kube-state-rs-watcher-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-rs-watcher
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kube-state-rs-watcher
  template:
    metadata:
      labels:
        app: kube-state-rs-watcher
    spec:
      serviceAccountName: kube-state-rs-watcher-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kube-state-rs-watcher
              topologyKey: "topology.kubernetes.io/region"
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kube-state-rs-watcher
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kube-state-rs-watcher
          image: kube-state-rs-watcher
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.2"
              memory: 200Mi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-state-rs-watcher-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kube-state-rs-watcher
